In [7]:
## Section 01: Importing Libraries

In [214]:
import tensorflow as tf
from tensorflow import keras 
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras import models
from tensorflow.keras import layers
from sklearn.preprocessing import StandardScaler
from tensorflow.keras import optimizers
from tensorflow.keras import losses
from tensorflow.keras import metrics

In [215]:
## End of Section 01

In [216]:
## Section 02: Reading the input dataset

In [217]:
df = pd.read_csv(r'C:\Users\Bilal Imran Butt\Desktop\PIAIC\dl_assignments\ML_Datasets-main\ionosphere_data.csv');
#print(df)
print(df.columns)

Index(['feature1', 'feature2', 'feature3', 'feature4', 'feature5', 'feature6',
       'feature7', 'feature8', 'feature9', 'feature10', 'feature11',
       'feature12', 'feature13', 'feature14', 'feature15', 'feature16',
       'feature17', 'feature18', 'feature19', 'feature20', 'feature21',
       'feature22', 'feature23', 'feature24', 'feature25', 'feature26',
       'feature27', 'feature28', 'feature29', 'feature30', 'feature31',
       'feature32', 'feature33', 'feature34', 'label'],
      dtype='object')


In [218]:
## End of section 02

In [219]:
## Section 03: Replacing 'NaN' valued data with the mean of its feature

In [220]:
#df.isnull()
#df.mean()
df.fillna(df.mean())
df.head()

feature1  feature2  feature3  feature4  feature5  feature6  feature7  \
0         1         0   0.99539  -0.05889   0.85243   0.02306   0.83398   
1         1         0   1.00000  -0.18829   0.93035  -0.36156  -0.10868   
2         1         0   1.00000  -0.03365   1.00000   0.00485   1.00000   
3         1         0   1.00000  -0.45161   1.00000   1.00000   0.71216   
4         1         0   1.00000  -0.02401   0.94140   0.06531   0.92106   

   feature8  feature9  feature10  ...  feature26  feature27  feature28  \
0  -0.37708   1.00000    0.03760  ...   -0.51171    0.41078   -0.46168   
1  -0.93597   1.00000   -0.04549  ...   -0.26569   -0.20468   -0.18401   
2  -0.12062   0.88965    0.01198  ...   -0.40220    0.58984   -0.22145   
3  -1.00000   0.00000    0.00000  ...    0.90695    0.51613    1.00000   
4  -0.23255   0.77152   -0.16399  ...   -0.65158    0.13290   -0.53206   

   feature29  feature30  feature31  feature32  feature33  feature34  label  
0    0.21266   -0.34090    0.42267   -0.54487    0.18641   -0.45300      g  
1   -0.19040   -0.11593   -0.16626   -0.06288   -0.13738   -0.02447      b  
2    0.43100   -0.17365    0.60436   -0.24180    0.56045   -0.38238      g  
3    1.00000   -0.20099    0.25682    1.00000   -0.32382    1.00000      b  
4    0.02431   -0.62197   -0.05707   -0.59573   -0.04608   -0.65697      g  

[5 rows x 35 columns]

In [221]:
# data shuffling
df = df.sample(frac = 1)
df.head()

feature1  feature2  feature3  feature4  feature5  feature6  feature7  \
317         1         0   1.00000  -0.24051   1.00000  -0.20253   0.87342   
201         1         0   1.00000  -0.28428   1.00000  -0.25346   0.94623   
185         1         0   0.84177   0.43460   0.50000   0.76160   0.09916   
95          1         0   0.79157   0.16851   0.00000   0.00000   0.56541   
346         1         0   0.83508   0.08298   0.73739  -0.14706   0.84349   

     feature8  feature9  feature10  ...  feature26  feature27  feature28  \
317  -0.10127   0.88608    0.01266  ...   -0.37975    0.84637   -0.05540   
201  -0.35094   1.00000   -0.30566  ...   -0.73333    0.35504   -0.76054   
185   0.93460  -0.37764    0.88186  ...   -0.28903    0.77937    0.07933   
95    0.06874   0.39468    1.00000  ...    0.80710   -0.34146    0.88248   
346  -0.05567   0.90441   -0.04622  ...   -0.04202    0.83479    0.00123   

     feature29  feature30  feature31  feature32  feature33  feature34  label  
317    1.00000   -0.06329    0.53165    0.02532    0.83544   -0.02532      g  
201    0.26352   -0.78239    0.16604   -0.73145    0.13994   -0.70000      g  
185    0.64135    0.42827    0.31435    0.62447   -0.00422    0.69409      g  
95    -1.00000    0.69401   -1.00000    0.12860    0.00000    0.00000      b  
346    1.00000    0.12815    0.86660   -0.10714    0.90546   -0.04307      g  

[5 rows x 35 columns]

In [222]:
# label encoding
dfNew = df.drop(['label','feature2'], axis=1)
label = df['label']
for c in range(len(label)):
    if label.iloc[c] == "g":
        label.iloc[c] = 1
    else:
        label.iloc[c] = 0
dfNew.head()
#print(label)

c:\users\bilal imran butt\appdata\local\programs\python\python37\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)


feature1  feature3  feature4  feature5  feature6  feature7  feature8  \
317         1   1.00000  -0.24051   1.00000  -0.20253   0.87342  -0.10127   
201         1   1.00000  -0.28428   1.00000  -0.25346   0.94623  -0.35094   
185         1   0.84177   0.43460   0.50000   0.76160   0.09916   0.93460   
95          1   0.79157   0.16851   0.00000   0.00000   0.56541   0.06874   
346         1   0.83508   0.08298   0.73739  -0.14706   0.84349  -0.05567   

     feature9  feature10  feature11  ...  feature25  feature26  feature27  \
317   0.88608    0.01266    1.00000  ...    0.62025   -0.37975    0.84637   
201   1.00000   -0.30566    0.92736  ...    0.49214   -0.73333    0.35504   
185  -0.37764    0.88186   -0.72363  ...    0.74895   -0.28903    0.77937   
95    0.39468    1.00000    0.38359  ...   -0.91574    0.80710   -0.34146   
346   0.90441   -0.04622    0.89391  ...    0.95378   -0.04202    0.83479   

     feature28  feature29  feature30  feature31  feature32  feature33  \
317   -0.05540    1.00000   -0.06329    0.53165    0.02532    0.83544   
201   -0.76054    0.26352   -0.78239    0.16604   -0.73145    0.13994   
185    0.07933    0.64135    0.42827    0.31435    0.62447   -0.00422   
95     0.88248   -1.00000    0.69401   -1.00000    0.12860    0.00000   
346    0.00123    1.00000    0.12815    0.86660   -0.10714    0.90546   

     feature34  
317   -0.02532  
201   -0.70000  
185    0.69409  
95     0.00000  
346   -0.04307  

[5 rows x 33 columns]

In [223]:
for c in dfNew.dtypes:
    print(c)

int64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64


In [224]:
dfNew = dfNew.astype('float64')

In [225]:
## Section 03 Ends Here

In [226]:
## Standardize the input data

In [228]:
## section 04: Splitting data into 50% train, 30% validate and 20% test

In [229]:
# Applying Train Test Split
X_train, X_test, y_train, y_test = train_test_split(dfNew, label, test_size=0.4, random_state=42)
#X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.29, random_state=42)

In [241]:
## Standardize the input data
#print(Y)
mean = X_train.mean(axis=0)
std = X_train.std(axis=0)
X_train -= mean
X_train /= std

X_test -= mean
X_test /= std

#X.head()
#Y.head()

In [242]:
X_train

feature1  feature3  feature4  feature5  feature6  feature7  feature8  \
109   0.34987  0.720214 -1.425942  0.766638 -1.811035  0.695890 -2.118175   
211   0.34987 -0.408942  0.112782  0.054626 -0.008790 -0.533260  0.110958   
240   0.34987 -0.825847  0.735976 -1.221199 -0.207478 -1.656724 -2.167334   
273   0.34987 -0.312536 -0.181597  0.004263 -0.178017  0.090804 -0.209228   
292   0.34987  0.403752 -0.176980  0.511257 -0.393097  0.546505 -0.239552   
..        ...       ...       ...       ...       ...       ...       ...   
36    0.34987  0.720214 -0.088111  0.783680 -0.233902  0.902878 -0.296614   
24    0.34987  0.720214 -0.241601  0.783680 -0.143180  0.902878 -0.338466   
114   0.34987  0.541209  1.794903 -2.684220  1.978067 -1.851152  0.834898   
110   0.34987  0.014484 -1.557157 -1.221199 -0.207478 -1.071819 -0.239552   
275   0.34987  0.060834  0.142459  0.323299 -0.131924  0.215387 -0.082476   

     feature9  feature10  feature11  ...  feature25  feature26  feature27  \
109  0.964595  -1.075084   0.937582  ...   0.422607  -1.300709   0.029740   
211  0.238245  -0.340053  -0.181763  ...  -0.004277   0.121689  -0.337865   
240 -1.032848  -0.340053  -0.687804  ...  -0.784288   1.061110  -0.886792   
273  0.143167  -0.289325   0.352580  ...   0.165145   0.416077   0.083184   
292  0.438729  -0.496897   0.444628  ...   0.806072  -0.235395   0.416414   
..        ...        ...        ...  ...        ...        ...        ...   
36   0.964595  -0.483990   0.899570  ...   0.881880  -0.124981   0.700688   
24   0.964595  -0.375083   0.937582  ...   0.806172  -0.418362   0.386261   
114 -0.924886   0.270044  -1.148551  ...  -0.611128   0.312417  -0.992710   
110  0.510636   1.712073   0.937582  ...  -0.611078   0.312375   0.908551   
275  0.185353  -0.350191   0.568407  ...   0.501386   0.043053   0.219788   

     feature28  feature29  feature30  feature31  feature32  feature33  \
109  -1.262869   0.764129  -1.824597   1.157112  -1.923269  -0.065059   
211   0.142511  -0.157962   0.145128  -0.009523   0.094692  -0.092706   
240  -1.668784  -0.625862   0.145128  -0.560153  -1.923269  -0.641575   
273   0.190305   0.191457   0.074297   0.324924   0.307829   0.507367   
292  -0.254738   0.510596  -0.293983   0.654991  -0.667936   0.604757   
..         ...        ...        ...        ...        ...        ...   
36   -0.155112   0.843459  -0.220295   0.859696  -0.310938   0.946557   
24   -0.362827   0.628150  -0.614713   0.320323  -0.435709   0.574269   
114   0.175111  -0.625862   0.145128  -0.676183   0.094692  -0.641575   
110  -1.557026  -0.846816  -1.690301  -0.676183   0.094692  -0.641575   
275   0.129917   0.687321   0.188895   0.446435  -0.049794   0.330956   

     feature34  
109  -1.592520  
211  -0.002072  
240   0.037154  
273  -0.136065  
292  -0.494730  
..         ...  
36   -0.407478  
24   -0.808323  
114   0.037154  
110   0.037154  
275  -0.063287  

[210 rows x 33 columns]

In [243]:
y_train
#validate

<tf.Tensor: shape=(210,), dtype=float32, numpy=
array([1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0.,
       1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1.,
       0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1.,
       0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1.,
       1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1.,
       1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 0.,
       1., 1., 1., 0., 0., 1.], dtype=float32)>

In [244]:
X_test

feature1  feature3  feature4  feature5  feature6  feature7  feature8  \
205   0.34987  0.537545 -0.302904  0.724716  0.178205  0.554403 -0.069444   
244   0.34987 -1.349922 -0.098158  0.783680  0.074217  0.674682 -0.278107   
112   0.34987 -0.480465 -1.513558 -1.221199 -0.207478  0.902878 -2.167334   
178   0.34987 -0.965084 -0.484887 -1.221199 -0.207478 -1.071819 -0.239552   
86    0.34987  0.048393  0.006906  0.322177 -0.438403  0.455767 -0.166797   
..        ...       ...       ...       ...       ...       ...       ...   
327   0.34987  0.720214  2.222168 -0.485409 -0.072893 -0.815246  1.547753   
267   0.34987 -0.129784 -1.511864  0.491569  1.001085  0.530174 -0.099113   
343   0.34987 -0.618212 -0.417621  0.169926 -0.260434  0.274826 -0.308451   
130   0.34987 -1.349922 -0.098158  0.762007 -0.703663 -0.698226 -0.343748   
93    0.34987 -2.471522  0.246665 -1.897766  1.396166 -0.044739 -0.508130   

     feature9  feature10  feature11  ...  feature25  feature26  feature27  \
205  0.788341  -0.400406   0.885850  ...   0.812212   0.374064   0.769057   
244 -1.032848  -0.340053   0.937582  ...  -0.611078   0.312375   0.908551   
112  0.764851   1.712073  -0.065037  ...  -0.260654   1.738696   0.908551   
178 -1.032848  -0.340053  -0.821398  ...  -0.480036   0.500608  -0.663624   
86   0.286224  -0.432974   0.313637  ...   0.805738  -0.004226   0.412061   
..        ...        ...        ...  ...        ...        ...        ...   
327 -1.583863   1.580655  -1.375952  ...   0.620280  -0.651440   0.632319   
267  0.098164  -0.007096  -0.244787  ...   0.254504   0.871430  -0.060835   
343  0.080068  -0.465623   0.266285  ...   0.139965   0.300545  -0.248431   
130 -1.032848  -0.340053   0.818728  ...  -0.611078   0.312375   0.908551   
93  -0.395883  -0.479824  -0.456533  ...   1.057610   1.689089  -0.206565   

     feature28  feature29  feature30  feature31  feature32  feature33  \
205   0.223053   0.988841  -0.086610   1.103195   0.213389   1.084963   
244  -1.668784  -0.625862   0.145128   1.157112   0.332368   1.075324   
112   0.580768  -0.625862   0.145128  -0.676183   0.094692  -0.641575   
178  -0.025818  -0.411410   0.334517  -0.629177  -0.002331  -0.322934   
86    0.068147   0.520032   0.189723   0.908059   0.170850   0.744715   
..         ...        ...        ...        ...        ...        ...   
327   0.049155   1.089753   2.114854   0.032752   0.099656  -0.305304   
267   0.685631   0.167027   0.707957   0.121007   0.686439   0.131424   
343   0.008460  -0.015309  -0.057872  -0.085275  -0.079599  -0.093501   
130  -0.148824  -0.625862   0.145128   1.157112  -0.428888  -0.093956   
93   -0.564586  -0.886121   0.364674  -0.632202   1.221118   0.355081   

     feature34  
205   0.163097  
244  -0.167454  
112   0.037154  
178   0.455771  
86    0.053320  
..         ...  
327   1.745581  
267   0.678258  
343  -0.140562  
130  -0.298493  
93   -0.155079  

[141 rows x 33 columns]

In [245]:
y_test

<tf.Tensor: shape=(141,), dtype=float32, numpy=
array([1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0.,
       0., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0.,
       0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0.,
       1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0.,
       1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1.,
       1., 1., 1., 0., 0.], dtype=float32)>

In [246]:
## End of Section 04

In [259]:
## Section 05: Building Model
print(X_train.shape[1])

33


In [254]:
def build_model():
    model = models.Sequential()
    model.add(layers.Dense(1, activation='relu', input_shape=(X_train.shape[1],)))
    model.add(layers.Dense(16, activation='relu'))
    model.add(layers.Dense(1, activation='sigmoid'))
    model.compile(optimizer=optimizers.RMSprop(lr=0.001), loss=losses.binary_crossentropy, metrics=[metrics.binary_accuracy])
    return model

In [255]:
## End of Section 05

In [256]:
## Section 06: Model Fitting

In [257]:
mdl = build_model()
#[print(i.shape, i.dtype) for i in model.inputs]
#[print(o.shape, o.dtype) for o in model.outputs]
#[print(l.name, l.input_shape, l.dtype) for l in model.layers]

In [258]:
#mdl.fit(X_train, y_train, epochs=100, batch_size=1, verbose=2,validation_data=(X_val,y_val))
y_train = tf.convert_to_tensor(y_train, dtype=tf.float32)
mdl.fit(X_train, y_train, epochs=100, batch_size=1, verbose=2)

Epoch 1/100
210/210 - 1s - loss: 0.6545 - binary_accuracy: 0.6524
Epoch 2/100
210/210 - 0s - loss: 0.6079 - binary_accuracy: 0.6524
Epoch 3/100
210/210 - 0s - loss: 0.5726 - binary_accuracy: 0.6524
Epoch 4/100
210/210 - 0s - loss: 0.5459 - binary_accuracy: 0.6524
Epoch 5/100
210/210 - 0s - loss: 0.5203 - binary_accuracy: 0.6571
Epoch 6/100
210/210 - 0s - loss: 0.5098 - binary_accuracy: 0.8190
Epoch 7/100
210/210 - 0s - loss: 0.4931 - binary_accuracy: 0.8190
Epoch 8/100
210/210 - 0s - loss: 0.4794 - binary_accuracy: 0.8190
Epoch 9/100
210/210 - 0s - loss: 0.4692 - binary_accuracy: 0.8286
Epoch 10/100
210/210 - 0s - loss: 0.4539 - binary_accuracy: 0.8286
Epoch 11/100
210/210 - 0s - loss: 0.4394 - binary_accuracy: 0.8429
Epoch 12/100
210/210 - 0s - loss: 0.4325 - binary_accuracy: 0.8571
Epoch 13/100
210/210 - 0s - loss: 0.4289 - binary_accuracy: 0.8619
Epoch 14/100
210/210 - 0s - loss: 0.4150 - binary_accuracy: 0.8714
Epoch 15/100
210/210 - 0s - loss: 0.3995 - binary_accuracy: 0.8810
Epoc

In [253]:
y_test = tf.convert_to_tensor(y_test, dtype=tf.float32)
mdl.evaluate(X_test,y_test)

5/5 [==============================] - 0s 760us/step - loss: 0.8884 - binary_accuracy: 0.8652


[0.8883588910102844, 0.8652482032775879]

In [124]:
y_test.iloc[1]

55.9

In [125]:
import math

In [126]:
math.sqrt(55.9)

7.476630257007497